# Generated by Django 3.0.7 on 2020-07-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(max_length=30, verbose_name='Mimetype')),
                ('videourl', models.URLField(verbose_name='Url')),
                ('video', models.FileField(blank=True, null=True, upload_to='Videos/')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='Thumbnails/videos/')),
            ],
        ),
    ]
