# Generated by Django 3.0.7 on 2020-07-13 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=50, verbose_name='Id')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(max_length=30, verbose_name='Mimetype')),
                ('imageurl', models.CharField(max_length=150, verbose_name='Url')),
                ('image', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
