# Generated by Django 3.0.7 on 2020-07-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photos',
            new_name='Images',
        ),
    ]
