# Generated by Django 3.0.7 on 2020-07-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='Thumbnails/photos/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Images/'),
        ),
    ]
