# Generated by Django 3.0.7 on 2020-06-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('s', 'Spotify'), ('f', 'Facebook'), ('t', 'twitter'), ('i', 'Github'), ('g', 'Google'), ('ig', 'instagram'), ('w', 'windows'), ('o', 'worpress'), ('y', 'youtube'), ('w', 'whatsapp')], max_length=30, verbose_name='Platform')),
                ('email', models.EmailField(default='kmishmael@gmail.com', max_length=50, verbose_name='Email')),
                ('name', models.CharField(default=None, max_length=50, verbose_name='Name')),
                ('username', models.CharField(max_length=30, verbose_name='Username')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
            ],
        ),
    ]
