# Generated by Django 3.0.7 on 2020-06-30 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(choices=[('Spotify', 'Spotify'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Github', 'Github'), ('Google', 'Google'), ('Instagram', 'Instagram'), ('Microsoft', 'Microsoft'), ('Wordpress', 'Wordpress'), ('Yputube', 'Youtube'), ('Whatsapp', 'Whatsapp')], max_length=30, verbose_name='Platform')),
                ('p_username', models.CharField(max_length=30, verbose_name='Username')),
                ('p_email', models.EmailField(max_length=30, verbose_name='Email')),
                ('p_name', models.CharField(max_length=30, verbose_name='Name')),
                ('p_password', models.CharField(max_length=30, verbose_name='Password')),
                ('f_class', models.CharField(max_length=30, verbose_name='Icon')),
            ],
        ),
    ]
