# Generated by Django 3.0.7 on 2020-07-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='s_name',
            field=models.CharField(choices=[('Spotify', 'Spotify'), ('Facebook', 'Facebook'), ('Twitter', 'Twitter'), ('Github', 'Github'), ('Google', 'Google'), ('Instagram', 'Instagram'), ('Microsoft', 'Microsoft'), ('Wordpress', 'Wordpress'), ('Youtube', 'Youtube'), ('Whatsapp', 'Whatsapp')], max_length=30, verbose_name='Platform'),
        ),
    ]
