# Generated by Django 3.0.7 on 2020-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20200701_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
