# Generated by Django 3.0.7 on 2020-07-01 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20200701_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platforms',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
